---
title: "DA.4 Hypervolumes"
author: "Joshua et al."
date: "2023-10-20"
output: html_document
---
# Packages
```{r echo = FALSE, print = FALSE, message = FALSE, warning = FALSE}
library("tidyverse")
library("BAT") # computes functional metrics based on Mammola and Cardoso (2020)
library("hypervolume") # computes hypervolumes based on XY
library("fastDummies") # create dummy columns for cetegorical traits

#packages for parallel computation
library("foreach")
library("future")
library("doFuture")
```

# Re-arranging data frame
```{r}
raw_traits <- readr::read_tsv("../Input data/PFTC6_Incline_clean_leaf_traits_2022.txt", guess_max = Inf)
traits <- select(raw_traits, c(ID, siteID, blockID, warming, species, trait, value)) %>% na.omit() %>%
  filter(trait %in% c("ldmc", "leaf_area_cm2", "leaf_thickness_mm", "plant_height_cm", "sla_cm2_g"))# one sample removed: DLL3549
rm(raw_traits)
# all rows in the comm matrix have to sum to 1. rownames = sampling units, colnames = species
# traits in the traits table should be scaled, centered and not highly correlated. rownames = species, colnames = traits.
# colnames in comm and rownames in trait have to match!
```

# Hypervolume based on treatment throughout sites (Level 1, scale first)
```{r, print = FALSE}
# This step calculates the mean value for each species, trait and treatment. It also removes 10 species that only occur in C or W.
trait_i <- traits %>% group_by(warming, species, trait) %>% summarise(mean_value = mean(value, na.rm = TRUE)) %>%
          pivot_wider(names_from = trait, values_from = mean_value)
trait_i <- trait_i %>% ungroup() %>% left_join(as.data.frame(table(trait_i$species)), by = c("species" = "Var1")) %>%
  filter(Freq == 2)
trait_CW <- traits %>% group_by(species, trait) %>% summarise(mean_value = mean(value, na.rm = TRUE)) %>%
          pivot_wider(names_from = trait, values_from = mean_value) # mean value per species irrespective of treatment
trait_CW <- trait_CW %>% mutate(warming = "CW") %>% semi_join(trait_i, by = "species") %>% ungroup()
trait_i <- trait_i %>% select(-c("Freq")) %>% rbind(trait_CW) %>% mutate(speciesID = paste(species, warming, sep = " "))
trait_i[,c(3:7)] <- scale(trait_i[,c(3:7)], center = T, scale = T) # scaling all mean values together. 

#This step creates the community matrix based on the trait tables. It does not matter for functional richness (Fric) computation if each species has abundance of 1 or 1/35 or 1/38 etc.
comm_all <- trait_i %>% select(c(warming, speciesID)) %>% dummy_cols(select_columns = "warming", remove_selected_columns = T) %>% column_to_rownames(var = "speciesID") %>% t()

trait_i <- trait_i %>% select(-c(warming, species)) %>% column_to_rownames(var = "speciesID")
trait_pca <- prcomp(x = trait_i, center = FALSE, scale. = FALSE) # center and scale already done in lines above
trait_pca <- trait_pca$x %>% as.data.frame() %>% select(c(1:3)) # primary 3 components account for 85.5 % of overall variation

# The for() loop calculates Fric for each treatment group (control, OTC, both) 100 times
out <- list()
for(i in 1:100) {
  set.seed(0+i)
  print(i)
  hp <- kernel.build(comm = comm_all, trait = trait_pca, distance = "euclidean", method.hv = "gaussian",
                             abund = FALSE, weight = NULL, axes = 0, convert = 0)
  out[[i]]  <- kernel.alpha(hp)
}

fric_CW <- as.data.frame(out)
colnames(fric_CW) <- c(1:100)
fric_CW <- fric_CW %>% t() %>% as.data.frame() %>% rename(Control = warming_C, OTC = warming_W, `all samples` = warming_CW)
fric_CW <- pivot_longer(fric_CW, cols = 1:3, names_to = "warming", values_to = "fric")

distr <- ggplot(fric_CW, aes(x = fric, color = warming)) + 
  geom_density(data = subset(fric_CW, warming == 'OTC'),fill = "red", alpha = 0.2) +
  geom_density(data = subset(fric_CW, warming == 'Control'),fill = "blue", alpha = 0.2) +
  geom_density(data = subset(fric_CW, warming == 'all samples'),fill = "green", alpha = 0.2) +
  theme_classic() + scale_colour_manual(name  = "", breaks=c("OTC", "Control", "all samples"), labels = c("OTC", "Control", "all samples"), values=c("red", "blue", "green")) +
  guides(color = guide_legend(override.aes = list(fill = c("red", "blue", "green")))) + theme(legend.position = c(0.6, 0.9)) +
  labs(title = NULL, x ='Functional richness', y ='density')
# print 400 x 300
```

# Site-specific hypervolumes -> effect of warming (Level 2)
```{r, print = FALSE}
trait_gud <- traits %>% filter(siteID == "Gudmedalen") %>% group_by(warming, species, trait) %>%
  summarise(mean_value = mean(value, na.rm = TRUE)) %>% pivot_wider(names_from = trait, values_from = mean_value)
trait_gud <- trait_gud %>% ungroup() %>% left_join(as.data.frame(table(trait_gud$species)), by = c("species" = "Var1")) %>%
  filter(Freq == 2) %>% mutate(speciesID = paste(species, "Gud", warming, sep = " "), siteID = paste("Gud", warming, sep = " "))
trait_gud[,c(3:7)] <- scale(trait_gud[,c(3:7)], center = T, scale = T)

trait_ulv <- traits %>% filter(siteID == "Ulvehaugen") %>% group_by(warming, species, trait) %>%
  summarise(mean_value = mean(value, na.rm = TRUE)) %>% pivot_wider(names_from = trait, values_from = mean_value)
trait_ulv <- trait_ulv %>% ungroup() %>% left_join(as.data.frame(table(trait_ulv$species)), by = c("species" = "Var1")) %>%
  filter(Freq == 2) %>% mutate(speciesID = paste(species, "Ulv", warming, sep = " "), siteID = paste("Ulv", warming, sep = " "))
trait_ulv[,c(3:7)] <- scale(trait_ulv[,c(3:7)], center = T, scale = T)

trait_skj <- traits %>% filter(siteID == "Skjelingahaugen") %>% group_by(warming, species, trait) %>%
  summarise(mean_value = mean(value, na.rm = TRUE)) %>% pivot_wider(names_from = trait, values_from = mean_value)
trait_skj <- trait_skj %>% ungroup() %>% left_join(as.data.frame(table(trait_skj$species)), by = c("species" = "Var1")) %>%
  filter(Freq == 2) %>% mutate(speciesID = paste(species, "Skj", warming, sep = " "), siteID = paste("Skj", warming, sep = " "))
trait_skj[,c(3:7)] <- scale(trait_skj[,c(3:7)], center = T, scale = T)

comm_all <- rbind(trait_gud, trait_ulv, trait_skj)

#_______________________________________________________________________________ beta-diversity

comm_gud <- trait_gud %>% select(c(siteID, speciesID)) %>% dummy_cols(select_columns = "siteID", remove_selected_columns = T) %>% column_to_rownames(var = "speciesID") %>% t()
trait_gud <- trait_gud %>% select(-c(warming, Freq, species, siteID)) %>% column_to_rownames(var = "speciesID")
trait_gud <- prcomp(x = trait_gud, center = FALSE, scale. = FALSE) # center and scale already done in lines above
trait_gud <- trait_gud$x %>% as.data.frame() %>% select(c(1:3)) # primary 3 components account for 83.7 % of overall variation

comm_ulv <- trait_ulv %>% select(c(siteID, speciesID)) %>% dummy_cols(select_columns = "siteID", remove_selected_columns = T) %>% column_to_rownames(var = "speciesID") %>% t()
trait_ulv <- trait_ulv %>% select(-c(warming, Freq, species, siteID)) %>% column_to_rownames(var = "speciesID")
trait_ulv <- prcomp(x = trait_ulv, center = FALSE, scale. = FALSE) # center and scale already done in lines above
trait_ulv <- trait_ulv$x %>% as.data.frame() %>% select(c(1:3)) # primary 3 components account for 83.7 % of overall variation

comm_skj <- trait_skj %>% select(c(siteID, speciesID)) %>% dummy_cols(select_columns = "siteID", remove_selected_columns = T) %>% column_to_rownames(var = "speciesID") %>% t()
trait_skj <- trait_skj %>% select(-c(warming, Freq, species, siteID)) %>% column_to_rownames(var = "speciesID")
trait_skj <- prcomp(x = trait_skj, center = FALSE, scale. = FALSE) # center and scale already done in lines above
trait_skj <- trait_skj$x %>% as.data.frame() %>% select(c(1:3)) # primary 3 components account for 83.7 % of overall variation

out <- list()
for(i in 1:100) {
  set.seed(0+i)
  print(i)
hvlist = kernel.build(comm = comm_gud, trait = trait_gud, distance = "euclidean", method.hv = "gaussian",
                             abund = FALSE, weight = NULL, axes = 0, convert = 0)
beta <- kernel.beta(hvlist)
out[[i]] <- paste(beta$Btotal[1], beta$Brepl[1], beta$Brich[1], sep = ";")
}
beta_div <- out %>% as.data.frame() %>% t() %>% as.data.frame()
beta_div <- beta_div %>% separate(col = V1, into = c('Btotal', 'Brepl', 'Brich'), sep = ";", remove = T) %>%
  mutate(Btotal = as.numeric(Btotal), Brepl = as.numeric(Brepl), Brich = as.numeric(Brich))
colMeans(beta_div)
# Gud = 0.27567, Ulv = 0.26041, Skj = 0.27812
# beta-diversity with 5 dimensions: Gud = 0.37758, Ulv = 0.51155, Skj = 0.36701
#_______________________________________________________________________________ alpha-diversity

trait_all <- rbind(trait_gud, trait_ulv, trait_skj)
rm(trait_gud, trait_skj, trait_ulv, comm_gud, comm_ulv, comm_skj, out, beta_div, hvlist, i, beta)
comm_all <- comm_all %>% select(c(siteID, speciesID)) %>% dummy_cols(select_columns = "siteID", remove_selected_columns = T) %>% column_to_rownames(var = "speciesID") %>% t()
rownames(comm_all) <- c("Gud C", "Gud W", "Skj C", "Skj W", "Ulv C", "Ulv W")

plan(multisession)
ptm <- proc.time()
fric_all <- foreach(i = 1:100, .combine = rbind, .options.future = list(seed = TRUE)) %dofuture% {
set.seed(0+i)
kernel.alpha(kernel.build(comm = comm_all, trait = trait_all, distance = "euclidean", method.hv = "gaussian",
                             abund = FALSE, weight = NULL, axes = 0, convert = 0))
}
proc.time() - ptm

fric_all <- as.data.frame(fric_all)
colMeans(fric_all)
```

# Treatment-specific hypervolumes -> differences between sites (Level 3)
```{r}
trait_OTC <- traits %>% filter(warming == "W") %>% group_by(siteID, species, trait) %>%
  summarise(mean_value = mean(value, na.rm = TRUE)) %>% pivot_wider(names_from = trait, values_from = mean_value)
trait_OTC <- trait_OTC %>% ungroup() %>% left_join(as.data.frame(table(trait_OTC$species)), by = c("species" = "Var1")) %>%
  filter(Freq == 3) %>% mutate(speciesID = paste(species, "OTC", substr(siteID, 1, 3), sep = " "),
                               siteID = paste(substr(siteID, 1, 3), "OTC", sep = " "))
trait_OTC[,c(3:7)] <- scale(trait_OTC[,c(3:7)], center = T, scale = T)

trait_C <- traits %>% filter(warming == "C") %>% group_by(siteID, species, trait) %>%
  summarise(mean_value = mean(value, na.rm = TRUE)) %>% pivot_wider(names_from = trait, values_from = mean_value)
trait_C <- trait_C %>% ungroup() %>% left_join(as.data.frame(table(trait_C$species)), by = c("species" = "Var1")) %>%
  filter(Freq == 3) %>% mutate(speciesID = paste(species, "C", substr(siteID, 1, 3), sep = " "),
                               siteID = paste(substr(siteID, 1, 3), "C", sep = " "))
trait_C[,c(3:7)] <- scale(trait_C[,c(3:7)], center = T, scale = T)

trait_all <- rbind(trait_OTC, trait_C)

comm_all <- trait_all %>% select(c(siteID, speciesID)) %>% dummy_cols(select_columns = "siteID", remove_selected_columns = T) %>% column_to_rownames(var = "speciesID") %>% t()
rownames(comm_all) <- c("Gud C", "Gud W", "Skj C", "Skj W", "Ulv C", "Ulv W")

trait_all <- trait_all %>% select(-c(Freq, species, siteID)) %>% column_to_rownames(var = "speciesID")
rm(trait_gud, trait_skj, trait_ulv)

trait_pca <- prcomp(x = trait_all, center = FALSE, scale. = FALSE) # center and scale already done in lines above
trait_pca <- trait_pca$x %>% as.data.frame() %>% select(c(1:3)) # primary 3 components account for 83.7 % of overall variation

plan(multisession)
ptm <- proc.time()
fric_all <- foreach(i = 1:100, .combine = rbind, .options.future = list(seed = TRUE)) %dofuture% {
set.seed(0+i)
kernel.alpha(kernel.build(comm = comm_all, trait = trait_pca, distance = "euclidean", method.hv = "gaussian",
                             abund = FALSE, weight = NULL, axes = 0, convert = 0))
}
proc.time() - ptm

fric_all <- as.data.frame(fric_all)
```

# Plotting Level 3
```{r}
fric_C <- fric_all1 %>% select(`Gud C`, `Skj C`, `Ulv C`)
fric_C <- pivot_longer(fric_C, cols = 1:3, names_to = "site", values_to = "fric")
fric_W <- fric_all1 %>% select(`Gud W`, `Skj W`, `Ulv W`)
fric_W <- pivot_longer(fric_W, cols = 1:3, names_to = "site", values_to = "fric")

distr <- ggplot(fric_W, aes(x = fric, color = site)) + 
  geom_density(data = subset(fric_W, site == 'Skj W'),fill = "darkblue", alpha = 0.2) +
  geom_density(data = subset(fric_W, site == 'Gud W'),fill = "blue", alpha = 0.2) +
  geom_density(data = subset(fric_W, site == 'Ulv W'),fill = "lightblue", alpha = 0.2) +
  theme_classic() + scale_colour_manual(name  = "", breaks=c("Skj W", "Gud W", "Ulv W"), labels = c("Skjelingahaugen", "Gudmedalen", "Ulvehaugen"), values=c("darkblue", "blue", "lightblue")) +
  guides(color = guide_legend(override.aes = list(fill = c("darkblue", "blue", "lightblue")))) + theme(legend.position = c(0.8, 0.9)) + labs(title = NULL, x ='Functional richness (OTC)', y ='density')
# print 400 x 300

```

# Hypervolume of all samples in the control plots **DEPRECATED**
```{r, print = FALSE}
# some species are over-represented
# how strongly are traits correlated? Do PCA if too correlated!
trait <- traits %>% filter(warming == "C") %>% select(c(ID, trait, value))
trait <- pivot_wider(trait, id_cols = ID, names_from = trait, values_from = value)
trait <- trait %>% column_to_rownames(var = "ID")  %>% na.omit() # 35 samples with incomplete trait data removed
trait[,1:5] <- scale(trait[,1:5], center = T, scale = T)

comm <- trait %>% mutate(all_sites = 1/688) %>% select(-c(ldmc, leaf_area_cm2, leaf_thickness_mm, plant_height_cm, sla_cm2_g)) %>% t()

# trait correlations
cor_matrix1 <- pairs.panels(trait[,1:5], smooth = TRUE, ellipse = FALSE, method = "spearman", hist.col = 5, stars = TRUE)
cor_matrix2 <- trait %>% cor(method = "spearman") %>% round(2) %>% abs() # same as pairs.panel
cor_matrix2[cor_matrix2 == 1] <- NA
#Spearman's ρ is 1 if correlation is monotonic and Pearson's r is 1 if correlation is monotonic and linear. If ρ > r,  correlation is monotonic but not linear.
test <- prcomp(trait, center = F, scale. = F)
summary(test)
set.seed(1)
hypervolume <- kernel.build(comm = comm, trait = trait, distance = "euclidean", method.hv = "gaussian",
                             abund = FALSE, weight = NULL, axes = 0, convert = 0)

fric <- kernel.alpha(hypervolume)
fric <- as.data.frame(fric)

```
