---
title: "Generalized linear models"
author: "Joshua et al."
date: "2024-12-02"
output: html_document
---

# Packages
```{r}
library("tidyverse")
```

```{r}
raw_traits <- readr::read_tsv("../Input data/PFTC6_Incline_clean_leaf_traits_2022.txt", guess_max = Inf) # updated version of this file has leaf area and SLA of Avenella flexuosa, Festuca vivipara, Nardus stricta, Festuca ovin and Festuca rubra doubled
chem_traits <- readr::read_tsv("../Input data/PFTC6_Incline_clean_chemical_traits_2022.txt", guess_max = Inf)
chem_traits$merged <- case_when(str_detect(chem_traits$ID_merged, "_") == TRUE ~ "merged") # updates 'merged' column to flag all merged samples
# I checked that only samples were merged from the same site, block and treatment
traits <- raw_traits %>% select(c(siteID, blockID, warming, species, trait, value)) %>% na.omit() %>%
  filter(trait %in% c("ldmc", "leaf_area_cm2", "leaf_thickness_mm", "plant_height_cm", "sla_cm2_g")) # one sample removed: DLL3549

chem_traits <- chem_traits %>% group_by(ID_merged, trait) %>% sample_n(1) # removes all duplicated samples
chem_traits <- chem_traits %>% ungroup() %>% select(c(siteID, blockID, warming, species, trait, value)) %>% na.omit() %>%
  filter(trait %in% c("c_percent", "n_percent", "c_n", "d15n", "d13c")) # no sample removed, but trait phosphorus percentage removed because of missing data

traits <- rbind(traits, chem_traits)
test <- as.data.frame(table(traits$trait))
#selected_sp <- traits %>% select(siteID, warming, species) %>% unique() %>% group_by(species) %>% mutate(Freq = n()) %>% filter(Freq == 6) # filtering species we have samples for in C and W for each site. n = 13. 2 sites n = 17
#selected_sp <- unique(selected_sp$species)
#traits <- traits %>% filter(species %in% selected_sp) # trait set with only 13 selected species. 37.3 % of data omitted
rm(test, chem_traits, raw_traits)

```

# Table transformation and data Normality
```{r}
trait_i <- traits %>% filter(trait %in% c("plant_height_cm", "leaf_area_cm2", "leaf_thickness_mm", "ldmc", "sla_cm2_g")) %>% group_by(siteID, blockID, warming, species, trait) %>% summarise(mean_value = mean(value, na.rm = TRUE)) %>% pivot_wider(names_from = trait, values_from = mean_value) %>% na.omit() # group_by(siteID, blockID, warming, species, trait) 

trait_i[,c(6:8)] <- log10(trait_i[,c(6:8)]) #

pairs.panels(trait_i[,c(5:9)], smooth = TRUE, ellipse = FALSE, method = "pearson", hist.col = 4, stars = TRUE, cex = 4)

```
