---
title: "Mixed Effect Models"
author: "Joshua et al."
date: "2024-12-02"
output: html_document
---

# Packages
```{r}
library("tidyverse")
library("psych") # pairs.panel
library("lme4")
library("MuMIn") # R2 values for lmer models
library("lmerTest") # p-values for lmer models
library("broom.mixed") # clean model output
```

#Loading and merging data tables
```{r}
raw_traits <- readr::read_tsv("../Input data/PFTC6_Incline_clean_leaf_traits_2022.txt", guess_max = Inf)
chem_traits <- readr::read_tsv("../Input data/PFTC6_Incline_clean_chemical_traits_2022.txt", guess_max = Inf)

chem_traits <- chem_traits %>% group_by(ID_merged, trait) %>% sample_n(1) 
chem_traits <- chem_traits %>% ungroup() %>% select(c(siteID, blockID, warming, species, trait, value)) %>% na.omit() %>%
  filter(trait %in% c("c_percent", "n_percent", "c_n", "d15n", "d13c")) # no sample removed, but trait phosphorus percentage removed because of missing data

traits <- raw_traits %>% select(c(siteID, blockID, warming, species, trait, value)) %>% na.omit() %>%
  filter(trait %in% c("ldmc", "leaf_area_cm2", "leaf_thickness_mm", "plant_height_cm", "sla_cm2_g")) # one sample removed: DLL3549
traits <- rbind(traits, chem_traits)

selected_sp <- traits %>% select(siteID, warming, species) %>% unique() %>% group_by(species) %>% mutate(Freq = n()) %>%
               filter(Freq >= 4 & species != "Achillea millefolium") # filtering species we have samples for in C and W for each site. n = 13. 2 sites n = 17. Not included is Achillea millefolium because it has warming samples only in Gud
selected_sp <- unique(selected_sp$species)

traits <- traits %>% filter(species %in% selected_sp) # trait set with only 17 selected species.

rm(chem_traits, raw_traits, selected_sp)
```

# Table transformation and data Normality
```{r}
# Trait values aggregated by block. Each species can have up to 30 data points (3 sites x 2 treatments x 5 blocks)
traits_w <- traits %>% group_by(siteID, blockID, warming, species, trait) %>% summarise(mean_value = mean(value, na.rm = TRUE)) %>% pivot_wider(names_from = trait, values_from = mean_value) #%>% na.omit()

# trait values aggregated by site. Each species can have up to 6 data points (3 sites x 2 treatments)
traits_w <- traits %>% group_by(siteID, warming, species, trait) %>% summarise(mean_value = mean(value, na.rm = TRUE)) %>% pivot_wider(names_from = trait, values_from = mean_value)

pairs.panels(traits_w[,c(5:14)], smooth = TRUE, ellipse = FALSE, method = "pearson", hist.col = 4, stars = TRUE, cex = 4)

traits_w[,c(5, 10:11, 13:14)] <- log10(traits_w[,c(5, 10:11, 13:14)]) # Reducing right skew of c_n, height, sla, lth and la
```

# GLMs all species
```{r}
# H ~ Warming1/0 + PRecip + (Warming* Precip) + Rand(Species)

# precipitation is an ordered three level factor: 1300 mm in Ulvehaugen, 2100 mm in Gudmedalen, 3600 mm in Skjelingahaugen
traits_w$precipitation <- case_when(traits_w$siteID == "Ulvehaugen" ~ "low", traits_w$siteID == "Gudmedalen" ~ "medium",
                                    traits_w$siteID == "Skjelingahaugen" ~ "high")
traits_w$precipitation <- factor(traits_w$precipitation, levels = c("low", "medium", "high"), ordered = TRUE)
min(traits_w$precipitation)
traits_w$warming <- as.factor(traits_w$warming)

lme_1 <- lmerTest::lmer(c_percent ~ warming + precipitation + warming * precipitation + (1 | species),
                    data = traits_w, na.action = na.omit)
null_model <- lme4::lmer(c_percent ~ (1 | species), data = traits_w, na.action = na.omit)

summary(lme_1)
summary_table <- tidy(lme_1) # with broom.mixed package
anova(lme_1)
r.squaredGLMM(lme_1)
anova(null_model, lme_1) # Performs Likelihood Ratio Test (LRT)

# Model diagnostics
plot(residuals(lme_1)) # Check residuals
plot(lme_1)
plot(fitted(lme_1), residuals(lme_1)) # Check fitted values vs. residuals


```