---
title: "Standardized Effect Size"
author: "Joshua"
date: "2023-10-13"
output: html_document
---

# Packages
```{r echo = FALSE, print = FALSE, message = FALSE}
library("tidyverse")
```

# Re-arranging data frame
```{r}
raw_traits <- readr::read_tsv("../Input data/PFTC6_Incline_clean_leaf_traits_2022.txt", guess_max = Inf)
traits <- select(raw_traits, c(siteID, blockID, warming, species, trait, value)) %>% na.omit() # one sample removed: DLL3549

# aggregated by site, block and experiment____________________________________________________________________________
traits1 <- aggregate(traits$value, by = traits[,1:5], FUN = na.omit(mean))
traits1 <- rename(traits1, mean_value = x)
traits1l <- aggregate(traits$value, by = traits[,1:5], FUN = na.omit(length))
traits1l <- rename(traits1l, n_obs = x)
traits1sd <- aggregate(traits$value, by = traits[,1:5], FUN = na.omit(var)) # defaults to sample variance, not population variance
traits1sd$x <- sqrt(traits1sd$x)
traits1sd <- rename(traits1sd, sd = x)

# aggregated by site and experiment__________________________________________________________________________________
traits2 <- aggregate(traits$value, by = traits[,c(1,3:5)], FUN = na.omit(mean))
traits2 <- rename(traits2, mean_value = x)
traits2l <- aggregate(traits$value, by = traits[,c(1,3:5)], FUN = na.omit(length))
traits2l <- rename(traits2l, n_obs = x)
traits2sd <- aggregate(traits$value, by = traits[,c(1,3:5)], FUN = na.omit(var)) # defaults to sample variance, not population variance
traits2sd$x <- sqrt(traits2sd$x)
traits2sd <- rename(traits2sd, sd = x)

traits3 <- cbind(traits2, traits2l$n_obs, traits2sd$sd)
traits3 <- rename(traits3, n_obs = `traits2l$n_obs`, sd = `traits2sd$sd`)
traits3$ID <- paste(traits3$siteID, traits3$species, traits3$trait, sep = "_")
traits3C <- filter(traits3, warming == "C") # Control
traits3OTC <- filter(traits3, warming == "W") # Warming

traits3C <- traits3C %>% rename(C_mean = mean_value, C_n = n_obs, C_sd = sd) %>% select(-c(warming))
traits3OTC <- traits3OTC %>% rename(OTC_mean = mean_value, OTC_n = n_obs, OTC_sd = sd) %>%
  select(-c(siteID, species, warming, trait))

traits4 <- full_join(traits3C, traits3OTC, by = "ID")
traits4 <- select(traits4, -c(ID))
traits4 <- filter(traits4, !is.na(traits4$siteID) & !is.na(traits4$OTC_mean))
traits4 <- traits4 %>% mutate(mean_dif = C_mean - OTC_mean, n_dif = C_n - OTC_n, sd_dif = C_sd - OTC_sd)

traits4$pooled_SD <- NA
for(i in 1:nrow(traits4)) {
  traits4$pooled_SD[i] <- if(traits4$n_dif[i] == 0)
  {sqrt((traits4$C_sd[i]^2+traits4$OTC_sd[i]^2)/2)} # pooled sd for equal group sizes
  else {sqrt(((traits4$C_n[i] - 1) * traits4$C_sd[i]^2 + (traits4$OTC_n[i] - 1) * traits4$OTC_sd[i]^2) / (traits4$C_n[i] + traits4$OTC_n[i] - 2))} # pooled sd for unequal group sizes
  }

traits4$SES <- (traits4$OTC_mean - traits4$C_mean) / traits4$pooled_SD # Cohen's d: number of SDs between the two means:
 # mean(group a) - mean(group b) divided by pooled standard deviation.  https://en.wikiversity.org/wiki/Cohen%27s_d

traits4$PR <- (traits4$OTC_mean - traits4$C_mean) / traits4$C_mean # Relative Distance Plasticity Index: shows the factor by which the trait value in the OTC increased or decreased, in comparison to the control plot

rm(traits1, traits1l, traits1sd, traits2, traits2l, traits2sd, traits3, traits3C, traits3OTC, i)
```

# Task: compute p-values for the mean differences to see which are significant

# Plotting SES values
```{r}
SES_sites <- traits4 %>% filter(trait %in% c("ldmc", "leaf_area_cm2", "leaf_thickness_mm", "plant_height_cm", "sla_cm2_g")) %>% select(c(1:3,5,8,14)) %>% na.omit()
SES_sites <- aggregate(SES_sites$SES, by = SES_sites[,c(1,3)], FUN = mean)
SES_sites <- SES_sites %>% rename(`mean SES` = x)
SES_sites$trait <- case_when(SES_sites$trait == "leaf_area_cm2" ~ "LA", SES_sites$trait == "leaf_thickness_mm" ~ "LTH", SES_sites$trait == "sla_cm2_g" ~ "SLA", SES_sites$trait == "plant_height_cm" ~ "H", SES_sites$trait == "ldmc" ~ "LDMC")
SES_sites$level <- case_when(SES_sites$`mean SES` < 0 ~ "negative", SES_sites$`mean SES` > 0 ~ "positive")

SES_plot <- ggplot(SES_sites, aes(x = siteID, y = `mean SES`, shape = level)) +  
  geom_point(size = 3) +
  scale_shape_manual(values = c(1, 16)) +
  geom_hline(yintercept=0, lty=2, size=0.25) +
  coord_flip() +
  xlab("") + ylab("Mean Cohen's d") +
  theme_bw() +
  guides(colour = "legend", shape = "none") +
  facet_grid(. ~ trait) +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.title = element_blank(),
        legend.position= "top",
        legend.text = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.x = element_text(angle=45, vjust=.5, size = 12),
        axis.text.y = element_text(vjust=.5, size = 12))

# print 800 x 400
```

# Species specific plasticity and succeptibility to warming
```{r}
distribution <- readr::read_tsv("../Input data/species classifications.txt", guess_max = Inf)

species_sd <- aggregate(traits$value, by = traits[,4:5], FUN = na.omit(var))
species_sd$x <- sqrt(species_sd$x)
species_sd <- rename(species_sd, sd = x)
species_mean <- aggregate(traits$value, by = traits[,4:5], FUN = na.omit(mean))
species_n <- raw_traits %>% group_by(ID) %>% select(c(species, ID)) %>% slice_sample(n = 1)
species_n <- as.data.frame(table(species_n$species))
species_n <- rename(species_n, species = Var1)
species_abs_SES <- traits4 %>% na.omit() %>% group_by(species) %>% summarise(mean_SES = mean(abs(SES)))

species_sd <- cbind(species_sd, species_mean[,3])
species_sd <- rename(species_sd, mean = `species_mean[, 3]`)
species_sd <- species_sd %>% mutate(rel_sd = sd / mean) %>% select(-c(sd, mean))
species_sd <- species_sd %>% filter(trait %in% c("ldmc", "leaf_area_cm2", "leaf_thickness_mm", "plant_height_cm", "sla_cm2_g"))

species_sd <- species_sd %>% group_by(species) %>% summarise(mean_sd = mean(rel_sd)) %>% left_join(species_n, by = "species") %>%
  left_join(distribution, by = "species") %>% left_join(species_abs_SES, by = "species")

rm(species_mean, species_n, distribution, species_abs_SES)
```

# plotting relationship between succeptibility to warming and species type
```{r}
p1 <- ggplot(species_sd, aes(x = as.factor(alpine), y = mean_SES)) + geom_boxplot(outlier.alpha = 0) + theme_classic() +
  geom_jitter(width = 0.3, height = 0, alpha = 0.3) +
  scale_y_continuous(breaks = c(0, 0.3, 0.6, 0.9, 1.2), limits = c(0, 1.2)) +
  scale_x_discrete(labels = c("Generalist", "Alpine")) + xlab("") + ylab("Mean SES per species") +
  theme(axis.text.x = element_text(size = 10), axis.text.y = element_text(size = 10))
# print 350 x 400

```